In [1]:
import pandas as pd

In [69]:
df = pd.read_csv('pulseoximeter.csv')

df

,encounter_id,device,probe_location,sample_number,saturation,pi
0,01a542fef90c977867f1016bb46772e233006183c5c879...,59,NaN,1.0,97.0,34.0
1,01a542fef90c977867f1016bb46772e233006183c5c879...,60,NaN,1.0,97.0,4.8
2,01a542fef90c977867f1016bb46772e233006183c5c879...,73,NaN,1.0,98.0,5.0
3,01a542fef90c977867f1016bb46772e233006183c5c879...,59,NaN,2.0,93.0,29.0
4,01a542fef90c977867f1016bb46772e233006183c5c879...,60,NaN,2.0,92.0,4.7
...,...,...,...,...,...,...
89399,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,NaN,26.0,79.0,10.0
89400,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,60,NaN,27.0,77.0,1.4
89401,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,NaN,27.0,78.0,11.0
89402,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,60,NaN,28.0,76.0,1.6
89403,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,NaN,28.0,78.0,10.0

In [70]:
# drop duplicates

df = df.drop_duplicates()

In [71]:
# identifying NaN values

df.count()

encounter_id      89336
device            89214
probe_location    43734
sample_number     89325
saturation        89336
pi                41581
dtype: int64

In [72]:
# drop irrelevant columns

df = df.drop(columns = ['probe_location','pi','device'])

In [73]:
# check if they are dropped

df.count()

encounter_id     89336
sample_number    89325
saturation       89336
dtype: int64

In [74]:
# drop all rows with NaN values

df.dropna(inplace = True)

In [75]:
# check if they are any more NaN values

df.count()

encounter_id     89325
sample_number    89325
saturation       89325
dtype: int64

In [78]:
# Find the mean saturation (SpO2) readings by aggregating the saturation readings across different devices of the same sample_number and encounter_id

df['sample_number'] = pd.to_numeric(df['sample_number'], errors='coerce')
df['saturation'] = pd.to_numeric(df['saturation'], errors='coerce')

# Group by both 'encounter_id' and 'sample_number' and calculate the mean saturation
df_agg = df.groupby(['encounter_id', 'sample_number'], as_index=False)['saturation'].mean()

In [80]:
df_agg

,encounter_id,sample_number,saturation
0,01a542fef90c977867f1016bb46772e233006183c5c879...,1.0,98.142857
1,01a542fef90c977867f1016bb46772e233006183c5c879...,2.0,93.857143
2,01a542fef90c977867f1016bb46772e233006183c5c879...,3.0,94.142857
3,01a542fef90c977867f1016bb46772e233006183c5c879...,4.0,94.571429
4,01a542fef90c977867f1016bb46772e233006183c5c879...,5.0,94.714286
...,...,...,...
18731,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,24.0,86.500000
18732,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,25.0,78.000000
18733,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,26.0,77.500000
18734,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,27.0,77.500000
18735,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,28.0,77.000000

In [64]:
df

,encounter_id,sample_number,saturation
0,01a542fef90c977867f1016bb46772e233006183c5c879...,1.0,97.0
1,01a542fef90c977867f1016bb46772e233006183c5c879...,1.0,97.0
2,01a542fef90c977867f1016bb46772e233006183c5c879...,1.0,98.0
3,01a542fef90c977867f1016bb46772e233006183c5c879...,2.0,93.0
4,01a542fef90c977867f1016bb46772e233006183c5c879...,2.0,92.0
...,...,...,...
89399,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,26.0,79.0
89400,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,27.0,77.0
89401,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,27.0,78.0
89402,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,28.0,76.0
89403,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,28.0,78.0

In [34]:
df

,encounter_id,device,sample_number,saturation
0,01a542fef90c977867f1016bb46772e233006183c5c879...,59,1.0,97.0
1,01a542fef90c977867f1016bb46772e233006183c5c879...,60,1.0,97.0
2,01a542fef90c977867f1016bb46772e233006183c5c879...,73,1.0,98.0
3,01a542fef90c977867f1016bb46772e233006183c5c879...,59,2.0,93.0
4,01a542fef90c977867f1016bb46772e233006183c5c879...,60,2.0,92.0
...,...,...,...,...
89399,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,26.0,79.0
89400,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,60,27.0,77.0
89401,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,27.0,78.0
89402,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,60,28.0,76.0
89403,ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...,59,28.0,78.0

In [43]:
# read patient.csv
df = pd.read_csv('patient.csv')

In [44]:
df

,patient_id,site_id,assigned_sex,race,ethnicity
0,016339afef154984949f8465ebdad00b578ca86a7a1c77...,ucsf-hypoxialab,Female,African American,Not Hispanic
1,03407c7885333bebd88456994a5cab3a94ae36301b9e16...,ucsf-hypoxialab,Female,Asian,Not Hispanic
2,035135a7d4276f08304acba081009d0bd369ff3e7ab633...,ucsf-hypoxialab,Female,Caucasian,Not Hispanic
3,086c5bb6be06dd4fdb32f43233fb8a5116f3de7e3ca0a2...,ucsf-hypoxialab,Male,African American,Not Hispanic
4,08e4c37178f47f878973d57ebbe0f9c33a2abf1d4a853a...,ucsf-hypoxialab,Female,Caucasian Other/Multiethnic,Not Hispanic
...,...,...,...,...,...
232,fd664382dea1e7748db2b266873abb75e727a4973ff5ae...,ucsf-hypoxialab,Male,Asian,Not Hispanic
233,fe766d0286222e73856d0d7e35a479138b4b9bdf040da4...,ucsf-hypoxialab,Male,Asian Other/Multiethnic,Not Hispanic
234,ff2266a3d5bf1d20dcfe211805a448164ed8ea8c88d5a5...,ucsf-hypoxialab,Female,Hispanic,Hispanic
235,ff9b6a312ed7757144eacadc4d047035ebdca320c3487e...,ucsf-hypoxialab,Female,African American,Not Hispanic
236,ffcfe0f5b1bd1a78dab6f3e2e716b5c30d6f98495b3aac...,ucsf-hypoxialab,Male,Asian,Not Hispanic

In [45]:
# drop duplicates

df.drop_duplicates(inplace = True)

In [46]:
# check for NaN values

df.count()

patient_id      237
site_id         237
assigned_sex    235
race            229
ethnicity       235
dtype: int64

In [47]:
# drop unnecessary columns

df = df.drop(columns = ['site_id','race','ethnicity'])

In [48]:
df.count()

patient_id      237
assigned_sex    235
dtype: int64

In [49]:
# drop NaN values

df.dropna(inplace = True)

In [50]:
df.count()

patient_id      235
assigned_sex    235
dtype: int64

In [51]:
df

                                            patient_id assigned_sex
0    016339afef154984949f8465ebdad00b578ca86a7a1c77...       Female
1    03407c7885333bebd88456994a5cab3a94ae36301b9e16...       Female
2    035135a7d4276f08304acba081009d0bd369ff3e7ab633...       Female
3    086c5bb6be06dd4fdb32f43233fb8a5116f3de7e3ca0a2...         Male
4    08e4c37178f47f878973d57ebbe0f9c33a2abf1d4a853a...       Female
..                                                 ...          ...
232  fd664382dea1e7748db2b266873abb75e727a4973ff5ae...         Male
233  fe766d0286222e73856d0d7e35a479138b4b9bdf040da4...         Male
234  ff2266a3d5bf1d20dcfe211805a448164ed8ea8c88d5a5...       Female
235  ff9b6a312ed7757144eacadc4d047035ebdca320c3487e...       Female
236  ffcfe0f5b1bd1a78dab6f3e2e716b5c30d6f98495b3aac...         Male

[235 rows x 2 columns]

In [52]:
# output csv

df.to_csv('clean_patient.csv',index = False)

In [14]:
import pandas as pd 

df = pd.read_csv("encounter.csv")


df.head()

,patient_id,encounter_id,encounter_date,age_at_encounter,warming,fitzpatrick,monk_fingernail,monk_dorsal,monk_palmar,monk_upper_arm,...,finger_l1_diameter,finger_l2_diameter,finger_l3_diameter,finger_l4_diameter,finger_l5_diameter,finger_r1_diameter,finger_r2_diameter,finger_r3_diameter,finger_r4_diameter,finger_r5_diameter
0,55475c97e020e3161c4c98884cacd4ae73bf48629373c6...,01a542fef90c977867f1016bb46772e233006183c5c879...,2218-10-03,25.0,1.0,3.0,B,B,A,B,...,12.0,10.0,9.5,9.0,8.0,12.0,10.0,10.0,9.0,8.5
1,e57c8296e892af1eb3833849501700b06fdfb5d7a5385a...,01b0a887f76a3f77a708ccff97cabb16b223e572c4bfd1...,2174-02-21,29.0,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a7aac8218c201dae762a6666177bedfdfc889d0d67eb51...,02093f14af09488db9e650db6130e55e214c1831adf4f6...,2129-05-08,26.0,0.0,4.0,E,F,E,F,...,13.0,12.0,13.0,11.5,10.0,13.0,12.0,13.0,11.5,10.0
3,898d5cec03e22881b32dcdbc0fe52c1d73dde114834b3b...,023153e2349d0b1fd2677b51e963194f83fe919e52c12b...,2182-07-22,37.0,1.0,1.0,A,B,A,C,...,13.0,11.0,11.0,10.5,9.0,13.0,11.0,11.0,10.5,9.0
4,244e495a1195bb5a7443e8f3fa095c67363861e02081e4...,0241a26f4be08b7312eab3099fb7e044376d7d433d69cc...,2151-12-19,26.0,NaN,3.0,B,B,A,C,...,12.0,11.0,11.0,10.0,9.0,11.0,8.0,9.0,8.0,7.0

In [16]:
df.count()

patient_id            907
encounter_id          907
encounter_date        907
age_at_encounter      901
warming               728
fitzpatrick           899
monk_fingernail       687
monk_dorsal           689
monk_palmar           689
monk_upper_arm        689
monk_forehead         689
right_ear_device      119
left_ear_device        11
forehead_device        23
finger_l1_device      251
finger_l2_device      426
finger_l3_device      359
finger_l4_device      389
finger_l5_device      271
finger_r1_device      292
finger_r2_device      461
finger_r3_device      430
finger_r4_device      462
finger_r5_device      344
finger_l1_diameter    656
finger_l2_diameter    657
finger_l3_diameter    657
finger_l4_diameter    656
finger_l5_diameter    656
finger_r1_diameter    657
finger_r2_diameter    657
finger_r3_diameter    657
finger_r4_diameter    657
finger_r5_diameter    657
dtype: int64

In [18]:
# drop duplicate records
print(df.shape[0])

df = df.drop_duplicates()

df.shape[0]

907

907

In [20]:
# extract patient_id, encounter_id, monk_fingernail, monk_dorsal, monk_palmar as identified features for model
df = df[["patient_id", "encounter_id", "monk_fingernail", "monk_dorsal", "monk_palmar"]]

df.head(5)

,patient_id,encounter_id,monk_fingernail,monk_dorsal,monk_palmar
0,55475c97e020e3161c4c98884cacd4ae73bf48629373c6...,01a542fef90c977867f1016bb46772e233006183c5c879...,B,B,A
1,e57c8296e892af1eb3833849501700b06fdfb5d7a5385a...,01b0a887f76a3f77a708ccff97cabb16b223e572c4bfd1...,NaN,NaN,NaN
2,a7aac8218c201dae762a6666177bedfdfc889d0d67eb51...,02093f14af09488db9e650db6130e55e214c1831adf4f6...,E,F,E
3,898d5cec03e22881b32dcdbc0fe52c1d73dde114834b3b...,023153e2349d0b1fd2677b51e963194f83fe919e52c12b...,A,B,A
4,244e495a1195bb5a7443e8f3fa095c67363861e02081e4...,0241a26f4be08b7312eab3099fb7e044376d7d433d69cc...,B,B,A

In [22]:
# identify attributes with NaN values

df.count()

patient_id         907
encounter_id       907
monk_fingernail    687
monk_dorsal        689
monk_palmar        689
dtype: int64

In [26]:
# drop NaN values
df.dropna(inplace=True)

print(df.shape[0])

687

In [28]:
# output to csv

df.to_csv("cleaned_encounter.csv", index=False)

# data preprocessing - merging

In [ ]:
import pandas as pd

directory = ''

files = {
    'devices': 'devices.csv',
    'pulseox': 'pulseoximeter.csv',
    'patient': 'patient.csv',
    'bloodgas': 'bloodgas.csv',
    'encounter': 'encounter.csv'
}

for var, filename in files.items():
    globals()[var] = pd.read_csv(directory + filename)
    print(f"'{filename}' read into dataframe '{var}'.")

'devices.csv' read into dataframe 'devices'.
'clean_pulseoximeter.csv' read into dataframe 'pulseox'.
'patient.csv' read into dataframe 'patient'.
'bloodgas.csv' read into dataframe 'bloodgas'.
'encounter.csv' read into dataframe 'encounter'.

/var/folders/zp/2s75n1h55lgc10s8tmcwq62c0000gn/T/ipykernel_57007/2951183320.py:14: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  globals()[var] = pd.read_csv(directory + filename)

In [67]:
pulseox['saturation'] = pd.to_numeric(pulseox['saturation'], errors='coerce')
pulseox.pivot_table(index=['encounter_id','device'],columns='sample_number',values='saturation',aggfunc='mean')

sample_number                                               1.0    2.0   3.0   \
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02    98.0   93.0  93.0
                                                   42.02    99.0   94.0  94.0
                                                   43.02    99.0   96.0  96.0
                                                   59       97.0   93.0  93.0
                                                   60       97.0   92.0  93.0
...                                                          ...    ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60       96.0   95.0  94.0
                                                   73      100.0   97.0  97.0
                                                   76      100.0   87.0  87.0
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59       99.0  100.0  97.0
                                                   60      100.0   99.0  98.0

sample_number                                              4.0   5.0   6.0   \
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02   94.0  94.0  88.0
                                                   42.02   94.0  95.0  86.0
                                                   43.02   96.0  97.0  91.0
                                                   59      94.0  94.0  87.0
                                                   60      94.0  93.0  87.0
...                                                         ...   ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60       NaN   NaN  92.0
                                                   73      97.0  97.0  88.0
                                                   76      89.0  93.0  78.0
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59      97.0  97.0  97.0
                                                   60      98.0  98.0  98.0

sample_number                                              7.0   8.0   9.0   \
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02   87.0  88.0  88.0
                                                   42.02   86.0  87.0  87.0
                                                   43.02   90.0  90.0  91.0
                                                   59      87.0  88.0  88.0
                                                   60      88.0  87.0  88.0
...                                                         ...   ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60      92.0  91.0  91.0
                                                   73      89.0  89.0  89.0
                                                   76      81.0  82.0  81.0
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59      88.0  88.0  88.0
                                                   60      89.0  89.0  90.0

sample_number                                              10.0  ...  23.0  \
encounter_id                                       device        ...
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02   79.0  ...  76.0
                                                   42.02   74.0  ...  68.0
                                                   43.02   81.0  ...  77.0
                                                   59      78.0  ...  74.0
                                                   60      78.0  ...  74.0
...                                                         ...  ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60      81.0  ...   NaN
                                                   73      73.0  ...  79.0
                                                   76      70.0  ...  80.0
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59      88.0  ...  88.0
                                                   60      90.0  ...   NaN

sample_number                                              24.0  25.0  26.0  \
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02   75.0  75.0   NaN
                                                   42.02   68.0  68.0   NaN
                                                   43.02   77.0  76.0   NaN
                                                   59      74.0  73.0   NaN
                                                   60      74.0   NaN   NaN
...                                                         ...   ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60      81.0  80.0   NaN
                                                   73      79.0  79.0   NaN
                                                   76      77.0  80.0   NaN
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59      87.0  79.0  79.0
                                                   60      86.0  77.0  76.0

sample_number                                              27.0  28.0  29.0  \
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02    NaN   NaN   NaN
                                                   42.02    NaN   NaN   NaN
                                                   43.02    NaN   NaN   NaN
                                                   59       NaN   NaN   NaN
                                                   60       NaN   NaN   NaN
...                                                         ...   ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60       NaN   NaN   NaN
                                                   73       NaN   NaN   NaN
                                                   76       NaN   NaN   NaN
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59      78.0  78.0   NaN
                                                   60      77.0  76.0   NaN

sample_number                                              30.0  31.0  32.0
encounter_id                                       device
01a542fef90c977867f1016bb46772e233006183c5c879b... 40.02    NaN   NaN   NaN
                                                   42.02    NaN   NaN   NaN
                                                   43.02    NaN   NaN   NaN
                                                   59       NaN   NaN   NaN
                                                   60       NaN   NaN   NaN
...                                                         ...   ...   ...
ff340351558c84be44dc642830770aeed2f91215f86f5f3... 60       NaN   NaN   NaN
                                                   73       NaN   NaN   NaN
                                                   76       NaN   NaN   NaN
ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a441... 59       NaN   NaN   NaN
                                                   60       NaN   NaN   NaN

[3704 rows x 32 columns]

In [19]:
print(f"Length of original dataframe:\t\t{len(bloodgas)}")
print(f"Number of exact row-wise duplicates:\t{len(bloodgas[bloodgas.duplicated(keep='first')])}")

b = bloodgas.drop_duplicates()

print(f"Number of rows after removal:\t\t{len(b)}")

Length of original dataframe:		32877
Number of exact row-wise duplicates:	526
Number of rows after removal:		32351

In [20]:
print(f"Length of original dataframe:\t{len(b)}")
print(f"Number of missing encounter_id:\t{b['encounter_id'].isna().sum()}")
b = b.dropna(subset='encounter_id')
print(f"Number of rows after removal:\t{len(b)}")

Length of original dataframe:	32351
Number of missing encounter_id:	257
Number of rows after removal:	32094

In [23]:
# selecting relevant fields
b = b[['patient_id', 'encounter_id', 'type', 'sample', 'so2']]

# filtering for type 1
b = b[b['type'] == 1]
b = b.drop(columns='type')

# renaming columns
b = b.rename(columns={'so2': 'SaO2'})

In [29]:
print(f"Number of NaNs in 'sample' column: {b[b.isna().any(axis=1)]['sample'].isna().sum()}")
print(f"Number of NaNs in 'SaO2' column: {b[b.isna().any(axis=1)]['SaO2'].isna().sum()}")

Number of NaNs in 'sample' column: 0
Number of NaNs in 'SaO2' column: 1378

In [75]:
b = b.dropna()

In [30]:
b['patient_id'].nunique()

221

In [77]:
b.to_csv('clean_bloodgas.csv',index=False)

In [2]:
pulseox['saturation'] = pd.to_numeric(pulseox['saturation'])

In [5]:
pulseox = pulseox.groupby(['encounter_id', 'sample'], as_index=False)['saturation'].mean()

In [10]:
pulseox

                                            encounter_id  sample  saturation
0      01a542fef90c977867f1016bb46772e233006183c5c879...       1   98.142857
1      01a542fef90c977867f1016bb46772e233006183c5c879...       2   93.857143
2      01a542fef90c977867f1016bb46772e233006183c5c879...       3   94.142857
3      01a542fef90c977867f1016bb46772e233006183c5c879...       4   94.571429
4      01a542fef90c977867f1016bb46772e233006183c5c879...       5   94.714286
...                                                  ...     ...         ...
18731  ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...      24   86.500000
18732  ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...      25   78.000000
18733  ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...      26   77.500000
18734  ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...      27   77.500000
18735  ffcbe159f5e8ce8e81465af70eea01fa2607dac1cd0a44...      28   77.000000

[18736 rows x 3 columns]

In [6]:
pulseox.to_csv('clean_pulseoximeter.csv')

In [ ]:
!nbmerge merged_datacleaning.ipynb datacleaning.ipynb > datacleaning_final.ip